codecov:
  require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "60...80"
  status:
    project:
      default:
        informational: true

    patch:
      default:
        informational: true
