[package]
org = "ballerina_examples"
name = "management_api"
version = "0.1.0"
distribution = "2201.13.4"

[[dependency]]
org = "ballerina"
name = "ai"
version = "1.15.0"

[build-options]
observabilityIncluded = true
