[plugin]
id = "workflow-compiler-plugin"
class = "io.ballerina.lib.workflow.compiler.WorkflowCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/workflow-compiler-plugin-0.3.1-SNAPSHOT.jar"
