[package]
org = "ballerina_usecases"
name = "sales_lead_qualification"
version = "0.1.0"
distribution = "2201.13.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "salesforce"
version = "8.4.0"

[[dependency]]
org = "ballerinax"
name = "slack"
version = "5.0.1"

[[dependency]]
org = "ballerinax"
name = "twilio"
version = "5.0.1"
