[package]
org = "ballerina_usecases"
name = "support_case_resolution"
version = "0.1.0"
distribution = "2201.13.4"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "salesforce"
version = "8.4.0"

[[dependency]]
org = "ballerinax"
name = "slack"
version = "5.0.1"

[[dependency]]
org = "ballerinax"
name = "googleapis.gmail"
version = "4.2.0"
